
import React from 'react';
import { 
  LayoutDashboard, 
  ShoppingCart, 
  Package, 
  Truck, 
  Users, 
  BarChart3, 
  Settings,
  Plus,
  Search,
  ArrowRight,
  Bike,
  MapPin,
  CheckCircle2,
  Clock,
  ChevronRight,
  TrendingUp,
  UserCircle,
  GripVertical,
  Edit3,
  Menu,
  MessageCircle,
  Share,
  Filter,
  Banknote,
  CreditCard,
  Zap,
  Printer,
  ChevronDown,
  ScanBarcode,
  UserPlus,
  MoreHorizontal,
  Minus,
  Trash2,
  X,
  RotateCw
} from 'lucide-react';

export const COLORS = {
  primary: '#00BFA5',
  primaryDark: '#00897B',
  secondary: '#263238',
  accent: '#FFD600',
  background: '#F3F4F6',
  white: '#FFFFFF',
  text: '#1F2937',
  muted: '#6B7280'
};

export const ICONS = {
  Dashboard: <LayoutDashboard size={20} />,
  Vender: <ShoppingCart size={20} />,
  Produtos: <Package size={20} />,
  Entregas: <Truck size={20} />,
  Usuarios: <Users size={20} />,
  Estatisticas: <BarChart3 size={20} />,
  Settings: <Settings size={20} />,
  Add: <Plus size={20} />,
  Search: <Search size={20} />,
  ArrowRight: <ArrowRight size={20} />,
  Bike: <Bike size={20} />,
  MapPin: <MapPin size={24} />,
  Check: <CheckCircle2 size={20} />,
  Clock: <Clock size={20} />,
  ChevronRight: <ChevronRight size={20} />,
  ChevronDown: <ChevronDown size={16} />,
  TrendingUp: <TrendingUp size={20} />,
  User: <UserCircle size={24} />,
  Grip: <GripVertical size={20} />,
  Edit: <Edit3 size={18} />,
  Menu: <Menu size={24} />,
  WhatsApp: <MessageCircle size={20} />,
  Share: <Share size={20} />,
  Filter: <Filter size={20} />,
  Cash: <Banknote size={24} />,
  Card: <CreditCard size={24} />,
  Pix: <Zap size={24} />,
  Printer: <Printer size={20} />,
  Barcode: <ScanBarcode size={24} />,
  UserPlus: <UserPlus size={24} />,
  MoreHorizontal: <MoreHorizontal size={20} />,
  Minus: <Minus size={16} />,
  Trash: <Trash2 size={24} />,
  Close: <X size={24} />,
  Refresh: <RotateCw size={20} />
};
